name: PR-CI

on :
  pull_request:
    branches: [main]

jobs:
  build:
    - name: PR- CI
      runs-on: ubuntu-latest
  
      steps:
      - name: Push code fromfeature to main
        uses: actions/checkout@v4   
      - name: Run demo
        run : echo "CI pass successfull"

